apiVersion: apps/v1
kind: Deployment

metadata:
  name: yt-downloader-deployment
  labels:
    app: yt-downloader

spec:
  replicas: 3

  selector:
    matchLabels:
      app: yt-downloader

  template:
    metadata:
      labels:
        app: yt-downloader

    spec:
      containers:
        - name: yt-downloader
          image: emirii1510/yt-downloader:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

